name: Build & Publish Docker Image

env:
  DOCKERHUB_TAG: 'jandi/webdav'

on:
  push:
    branches:    
      - main
  schedule:
    - cron:  '5 15 * * 5'

jobs:
  main:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set cache buster suffix
        id: cache_buster
        run: |
          if [ ${{ github.event_name }} == 'schedule' ]
          then
            echo "Scheduled run. Disable cache."
            echo "::set-output name=suffix::-no-cache"
          else
            echo "Non-scheduled run. Enable cache."
            echo "::set-output name=suffix::"
          fi
      -
        name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_TAG }}:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_TAG }}${{ steps.cache_buster.outputs.suffix }}
          cache-to: type=inline
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      -
        name: Image digests
        run: |
          echo image digest: ${{ steps.docker_build.outputs.digest }}